services:
  db:
    platform: linux/amd64
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - calendarium
    volumes:
      - calendarium_db:/var/lib/postgresql

volumes:
  calendarium_db:

networks:
  calendarium: