name: Linting

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  CI_TOKEN: ${{ secrets.CI_TOKEN }}
  CI_USER: ${{ secrets.CI_USER }}

jobs:
  lint:
    timeout-minutes: 10
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure git for private repository
        run: git config --global url."https://${CI_TOKEN}@github.com".insteadOf "https://github.com"

      - name: run lint
        uses: golangci/golangci-lint-action@v8
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          version: v2.1
