name: Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  CI_TOKEN: ${{ secrets.CI_TOKEN }}
  CI_USER: ${{ secrets.CI_USER }}

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  test:
    timeout-minutes: 10
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: go.mod

      - name: test
        run: |
          go run gotest.tools/gotestsum@latest \
            --junitfile unit-tests.xml \
            --format pkgname -- -coverprofile=coverage.out $(go list ./... | grep -Ev '(./cmd/|./*/testutil/|./*/mocks)')

      - name: octocov report
        uses: k1LoW/octocov-action@1ad702b3118b6a055c00b01db68ca0d9f6641dbc # v1.4.0

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: unit-tests.xml
        if: always()
